### ISSUE TITLE
Where to mention package information?

### ISSUE THREAD

**Issue by jubalh** [zapzap-linux/zapzap#27]
I [packaged](https://build.opensuse.org/package/show/network:im:whatsapp/zapzap) zapzap for openSUSE. I'm unsure whether the right place to add the information about it would be under `Downloads`, `Packaging` or adding a [repology](https://repology.org/project/zapzap/versions) bade to cover all distros in one shot.

**Comment by rafatosta** [comment]
Hello, congratulations on the initiative. 
Unfortunately I am unable to officially support other forms of packaging due to the short time to test. Flatpak makes my life easier because it is a controlled environment and will work exactly the same regardless of distribution.

As I use Fedora Workstation, it is easier to test and adjust the particularities. And there are some that are different in relation to the flatpak. 

But if you want to contribute by making contractions for OpenSuse, I will put the link on the website and in the readme.

**Comment by rafatosta** [comment]
I saw that there is a package for AUR. NO Arch gives me headaches because it causes bugs that I can't reproduce in my environment and it's difficult to make corrections.

**Comment by rafatosta** [comment]
Soon, I will put your repertoire on the website and in the project readme. Thank you very much for your collaboration
