### ISSUE TITLE
Pixmap doesn't work properly to show icons and images

### ISSUE THREAD

**Issue by igoutta** [zapzap-linux/zapzap#9]
I'm builiding from the source but I can't find really understand why Qpixmap doesn't created the image from the source. 

Here is the screenshot. 

![image](https://github.com/zapzap-linux/zapzap/assets/10776042/6eb7981c-2a4e-4d7b-b06e-e92660868277)

Here is the log:

[Full log while open](https://pastebin.com/N5p6uGbM)

I'm using Arch with kernel Linux 6.5.9-zen2-1-zen x86_64

**Comment by rafatosta** [comment]
**_First, see #6_** 

The log is very clear, not finding the path of images.It turns out that this problem does not happen in the version of FlatPak or Fedora.So it must be something related to the Arch, as the Aur package has the same behavior.

A possible solution is to change the form of access to images and use .qrc files with compiled images.Unfortunately I don't have much time to support Flathub or Fedora.

**Use the [FlatPak](https://flathub.org/apps/com.rtosta.zapzap) version and be happy!**
